### ISSUE TITLE
Please include the bug tracker in the docs

### ISSUE THREAD

**Issue by cpansprout** [jberger/Mojo-ACME#5] opened 2016-05-04 21:01 UTC
If I am viewing the Mojo::ACME documentation with perldoc, I can’t tell immediately where to report bugs, because the bug tracker is only listed in META.*, which do not get installed. It would be kinder to users if you could list it also in the docs.

(A README file is also a nice courtesy that fewer people are bothering with these days. People new to Perl and CPAN should, if they find the tarball, be able to install and use your module without knowing about the cpan client, metacpan.org, etc.)

**Comment by jberger** [comment] 2016-05-17 20:43
I don't see the value in including a bugtracker in the pod when it already lists the repository which contains the tracker. I already have to essentially duplicate this information in the META.

There is a README in the github repo but it is just (a) duplicate of the main module's pod and (b) not included in the tarball because metacpan improperly displays it if included (or at least did).

**Closed as completed by jberger** 2016-05-17 20:43 UTC
